---
default:
  interruptible: true

stages:
  - install
  - build
  - docker
  - post

variables:
  GO_VERSION: 1.24-alpine
  TASK_X_REMOTE_TASKFILES: 1
  GO_COMMAND_RUNNER: task --yes
  DOCKER_IMAGE_NAME: cenk1cenk2/beamer

include:
  - project: devops/pipes
    file: /templates/go.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-manifest-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/update-docker-hub-readme.gitlab-ci.yml

docker-build:
  stage: docker
  extends: .docker-build-dockerhub
  variables:
    DOCKER_IMAGE_TAGS: latest
  dependencies:
    - build
  only:
    refs:
      - main

update-docker-hub-readme:
  stage: post
  extends: .update-docker-hub-readme
  variables:
    README_DESCRIPTION: |
      Pull a configuration at the start of the container.
  dependencies: []
  only:
    refs:
      - main
